services:
  # Ứng dụng NodeJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goldprice-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka
      - redis
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/goldprice
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=gold-price-app
      - KAFKA_TOPIC=gold-price-updates
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - goldprice-network

  # Cơ sở dữ liệu MongoDB
  mongodb:
    image: mongo:latest
    container_name: goldprice-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - goldprice-network

  # Zookeeper (cần thiết cho Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: goldprice-zookeeper
    ports:
      - "2181:2181"
    networks:
      - goldprice-network

  # Message Broker Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: goldprice-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "gold-price-updates:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - goldprice-network

  # Redis cho caching
  redis:
    image: redis:latest
    container_name: goldprice-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - goldprice-network

# Volume để lưu trữ dữ liệu
volumes:
  mongodb_data:
  redis_data:

    # Network để kết nối các dịch vụ
networks:
  goldprice-network:
    driver: bridge
