services:
  zookeeper:
    container_name: "zookeeper"
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
     - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.6
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - BITNAMI_DEBUG=true
      # Không khai báo process.roles để tránh kích hoạt KRaft
      - KAFKA_BROKER_ID=1
      # Kết nối tới Zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Cấu hình listener
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # Giao thức bảo mật
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Cho phép PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Số lượng replica cho offset topic
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT_INTERNAL://:9092,PLAINTEXT_EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  app:
    build: .
    container_name: gold-price-app
    depends_on:
      - mongodb
      - kafka
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
  kafka_data:
  zookeeper_data: