version: '3.8'

services:
  # Application service
  app:
    container_name: "Application"
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=goldprice
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - timescaledb
      - redis
      - kafka
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - gold-price-network

  # TimescaleDB service
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goldprice
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - gold-price-network

  # Redis service for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gold-price-network

  # Zookeeper service (required for Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - gold-price-network

  # Kafka service for pub-sub
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "gold-price-updates:6:1"  # format: topic_name:partitions:replicas
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: "6"  # Default số partition cho topics tự động tạo
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"  # Replica factor cho dev
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gold-price-network

networks:
  gold-price-network:
    driver: bridge

volumes:
  timescaledb-data:
  redis-data:
